version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.0
    - 4.5.1
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: file-loader
    versions:
    - 6.2.0
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: yargs-parser
    versions:
    - 13.1.2
  - dependency-name: react-dom
    versions:
    - 16.13.1
